### ISSUE TITLE
Not centered on the screen

### ISSUE THREAD

**Issue by mhennessie** [chrstphrknwtn/grid-clock-screensaver#2]
Is there any way to make it vertically centered on a 1920x1200 screen. Looks like it would be fine if it were 1920x1080 but the extra 120px have it shifted up. It is nit-picking but just curious.

![screen shot 2016-12-27 at 1 17 07 pm](https://cloud.githubusercontent.com/assets/8999894/21505605/dae449c0-cc36-11e6-8e3c-76746204cc76.png)

**Comment by chrstphrknwtn** [comment]
Late response... but this is due to the grid being 16x15, and the styles ensuring it's square on any format of display (portrait for example).

I'm sure it's possible to fix it, but the clock being perfectly entered may also make it looks like it's sitting too low also.
