### ISSUE TITLE
Screensaver only "unlockable" using CTRL or SHIFT or Mouse

### ISSUE THREAD

**Issue by simschla** [chrstphrknwtn/grid-clock-screensaver#3]
I use grid-clock on my macbook pro 13" with touchbar. 

When the screensaver activates, I cannot open the pw-entry/login screen by pressing any key on the keyboard, it only works when pressing SHIFT or CTRL. It also works when using the mouse/touchpad. Pressing any other key on the keyboard, however, keeps the screensaver active.

Are you, maybe by accident, capturing all the other key presses?

**Comment by chrstphrknwtn** [comment]
_Should_ be fixed in 3f0d018e71611d388ce8f17a26a3013f22727ce6 - it appears to work correctly / like other screensavers now.
