### ISSUE TITLE
Doesn't work on MacOs Mojave 10.14

### ISSUE THREAD

**Issue by jesuscreyes** [chrstphrknwtn/grid-clock-screensaver#6]
![not_working](https://user-images.githubusercontent.com/9061700/47528089-20df6380-d859-11e8-97bb-5cfa2db57b51.png)

**Comment by chrstphrknwtn** [comment]
@jesuscreyes Rebuilt on my machine (running Mojave) and tested... hopefully should work for you now.

https://github.com/chrstphrknwtn/grid-clock-screensaver/releases/tag/0.0.5

Can't recall if the previous version was code-signed or not... this latest one isn't, so you might have to do the right-click and open thing to bypass the macOS security stuff.

**Comment by KennyV** [comment]
I didn't have the issue above. Installed the latest release anyway and confirm it's running perfectly fine on MacOS 10.14.3.
Thank you for this beautiful screensaver and excellent support !

**Comment by chrstphrknwtn** [comment]
Cool, thanks for the feedback @KennyV!

**Comment by ds2606** [comment]
Hi, 0.0.5 isn't working for me on Mojave 10.14.3 :( Happy to provide failure details if that's of use. Thanks for a gorgeous and useful screensaver.

Best,
Dan

**Comment by martindavid** [comment]
I still have this issue on my machine. I just update my os to the latest one OSX 10.14.3, but it doesn't work

**Comment by diegofernandezmrf** [comment]
@martindavid try to open it. You will probably receive the same message. Then go to Preferences > Security & Privary > General and you should see a message about Grid Clock, click the Allow anyway and voilà.
