### ISSUE TITLE
Screensaver does not work on Apple Silicon

### ISSUE THREAD

**Issue by thejarlid** [chrstphrknwtn/grid-clock-screensaver#8]
Similar to issue #6 on Apple Silicon with the same message. Unfortunately the fix for that issue does not solve it on an M1 Pro MacBook running macOS Monterey

**Comment by notverypc** [comment]
I have this running on a Apple Silicon M1 MacBook Pro running Monterey using these steps:
https://github.com/chrstphrknwtn/grid-clock-screensaver/issues/6#issuecomment-583119354
